services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: peerdeliver-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: peerdeliver
      POSTGRES_PASSWORD: peerdeliver_dev
      POSTGRES_DB: peerdeliver
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
